project_id = "kdsdytletfvbgcxuduqb"

[auth]
# Add production domain to allowed origins
enabled = true
# Enable email confirmations only if needed
enable_confirmations = false

[auth.email]
# Configure email settings for production
enable_signup = true
double_confirm_changes = true
enable_confirmations = false